"""Ajout de la clé étrangère user_id à la table document

Revision ID: 969cad55d411
Revises: 3c900b83eea1
Create Date: 2025-03-13 13:11:51.310430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '969cad55d411'
down_revision = '3c900b83eea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc_content', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('doc_insert_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('doc_updated_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('doc_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.alter_column('doc_format',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('file_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_document_user', 'users', ['user_id'], ['id'])
        batch_op.drop_column('updated_date')
        batch_op.drop_column('id')
        batch_op.drop_column('insert_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insert_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('updated_date', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint('fk_document_user', type_='foreignkey')
        batch_op.alter_column('file_path',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('doc_format',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False)
        batch_op.alter_column('doc_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.drop_column('user_id')
        batch_op.drop_column('doc_updated_date')
        batch_op.drop_column('doc_insert_date')
        batch_op.drop_column('doc_content')

    # ### end Alembic commands ###
