"""Ajout des champs job_title, department, phone et work_location

Revision ID: 111119408034
Revises: ae1caee2d95f
Create Date: 2025-03-15 23:54:34.837699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111119408034'
down_revision = 'ae1caee2d95f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('work_location', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('work_location')
        batch_op.drop_column('phone')
        batch_op.drop_column('department')
        batch_op.drop_column('job_title')

    # ### end Alembic commands ###
